name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:mbed-os-6.15-latest

    env:
      # The list of projects to run on. This should just run for each dir that includes a mbed_app.json
      PROJECTS: bms

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependencies for all projects
    - name: Install dependencies
      shell: bash
      run: |
        for PROJECT in $PROJECTS; do
          pushd $PROJECT
          make deps
          popd
        done

    # Compile all projects
    - name: Compile
      shell: bash
      run: |
        for PROJECT in $PROJECTS; do
          pushd $PROJECT
          make test
          popd
        done
