name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:mbed-os-6.15-latest

    strategy:
      matrix:
        # The list of projects to run on. This should just run for each dir that includes a mbed_app.json
        project: [bms]
        # The build profile to run on
        profile: [debug, release]
        # The mbed target to build for
        target: [LPC1768]

        # Add STM32F303 target for bms
        include:
          - project: bms
            profile: debug
            target: NUCLEO_F303K8
          - project: bms
            profile: release
            target: NUCLEO_F303K8


    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependencies for all projects
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ matrix.project }}
        make deps

    # Compile all projects
    - name: Compile
      shell: bash
      run: |
        cd ${{ matrix.project }}
        make build
